server:
  port: 8080
spring:
#  profiles: ide
  data:
    mongodb:
      uri: mongodb+srv://mon:qazwsxedc@blancesheetcluster.pzfo5.mongodb.net/balance_sheet?retryWrites=true&w=majority
      database: balance_sheet
